<div>
    <div id="load-title">notes</div>
    <div id="load-subtitle">notes</div>
    <div id="load-content"><a href="<?php echo $this->baseUrl('notes/AlgGeomNote.pdf'); ?>">algebraic geometry</a><br />
<a href="<?php echo $this->baseUrl('notes/AlgTopNotes.pdf'); ?>">algebraic topology</a><br />
<a href="<?php echo $this->baseUrl('notes/CatTheoryNotes.pdf'); ?>">category theory</a><br />
<a href="<?php echo $this->baseUrl('notes/HomotopyNotes.pdf'); ?>">homotopy</a><br />
<a href="<?php echo $this->baseUrl('notes/RepresentationNotes.pdf'); ?>">representation theory</a></div>
</div>