<div>
    <div id="load-title">notes</div>
    <div id="load-subtitle">notes</div>
    <div id="load-content"><p class="lspace"><a href="<?php echo $this->baseUrl('pnotes/AlgGeomNote.pdf'); ?>">algebraic geometry</a><br />
<a href="<?php echo $this->baseUrl('pnotes/AlgTopNotes.pdf'); ?>">algebraic topology</a><br />
<a href="<?php echo $this->baseUrl('pnotes/CatTheoryNotes.pdf'); ?>">category theory</a><br />
<a href="<?php echo $this->baseUrl('pnotes/HomotopyNotes.pdf'); ?>">homotopy</a><br />
<a href="<?php echo $this->baseUrl('pnotes/RepresentationNotes.pdf'); ?>">representation theory</a></p></div>
</div>