<?php $this->title = 'notes';
	  $this->subTitle = 'notes'; ?>

<p class="lspace"><a href="<?php echo $this->baseUrl('notes/AlgGeomNote.pdf'); ?>">algebraic geometry</a><br />
<a href="<?php echo $this->baseUrl('notes/AlgTopNotes.pdf'); ?>">algebraic topology</a><br />
<a href="<?php echo $this->baseUrl('notes/CatTheoryNotes.pdf'); ?>">category theory</a><br />
<a href="<?php echo $this->baseUrl('notes/HomotopyNotes.pdf'); ?>">homotopy</a><br />
<a href="<?php echo $this->baseUrl('notes/RepresentationNotes.pdf'); ?>">representation theory</a></p>