<?php $this->title = "error";
			$this->subTitle = "an error has occured!";
?>

<p class="lspace"><?php echo strtolower($this->message) ?></p>

<?php if (isset($this->exception)): ?>
 
<p class="lspace"><b>exception information:</b><br />
<?php echo $this->exception->getMessage() ?>
</p>

<p class="lspace"><b>stack trace:</b><br />
<pre><?php echo $this->exception->getTraceAsString() ?>
 </pre></p>

<p class="lspace"><b>request parameters:</b><br />
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre></p>

<?php endif ?>
